---
title: "Dash"
output: 
  flexdashboard::flex_dashboard:
    logo: www/paper_stack_icon_2.png
    orientation: columns
    vertical_layout: fill
    theme: cerulean
runtime: shiny
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(lubridate)
library(RPostgreSQL) # connects to database
library(plotly) # allows for web friendly graphs
library(DT) # allows for web friendly data table
library(viridis) # plot color

# Theme set for all plots
theme_set(
  theme_minimal() +
    theme(legend.position = "right"))

```


```{r connection to database, include = FALSE}

db <- dbConnect(drv = "PostgreSQL", 
                 dbname = "nors",
                 host = "localhost",
                 port = 5432,
                 user = "psm",
                 password = "admin")

```

```{r}

data <- reactive({dbGetQuery(db,sqlInterpolate(ANSI(),
                                "SELECT
                                  vat_number, account,year,month,value
                                FROM
                                  ( SELECT
                                        vat_number, account,year,month,value
                                    FROM
                                        statements
                                    WHERE
                                        account LIKE 'A00126'OR
                                        account LIKE 'A00139'OR
                                        account LIKE 'A00156'OR
                                        account LIKE 'A00125'OR
                                        account LIKE 'A00149'OR
                                        account LIKE 'A00141'OR
                                        account LIKE 'A00124'OR
                                        account LIKE 'A00018'OR
                                        account LIKE 'A00127'OR
                                        account LIKE 'A00131'OR
                                        account LIKE 'A00001'OR
                                        account LIKE 'A00006'
                                    ) AS t
                                WHERE
                                  vat_number = ?vat;",
                                vat = input$company_select)) %>%
    spread(account,value) %>%
    mutate(
      kpi0001 = A00139/A00126,
      kpi0002 = (A00125 - A00156)/1000,
      kpi0003 = A00125/A00156,
      kpi0004 = (A00149 + A00141 - A00124)/A00018,
      kpi0005 = A00139/A00127,
      kpi0006 = A00131/A00127,
      kpi0007 = (A00001-A00006)/A00001,
      kpi0008 = A00018/A00001
      ) %>%
    mutate(date = ymd(paste0(year,"-",month,"-01"))) %>%
    select(-vat_number, -year, -month) %>%
    select(date,everything()) %>%
    arrange(desc(date))})

```

Sidebar {.sidebar}
====================

```{r}
company <- dbGetQuery(db,"SELECT vat_number, name FROM company;")
Encoding(company$name) <- "UTF-8"

choices <- split(company$vat_number,company$name)

div(style = "font-size:9pt",
    selectInput("company_select", h5("Select company"), 
                       choices = choices, selected = "Galius"))


```


Overview
=======================================================================

Column {data-width=333}
-----------------------------------------------------------------------

### Autonomia financeira

```{r}

renderPlotly(
  data() %>%
  ggplot(aes(x = date, y = abs(kpi0001), group = 1)) +
  geom_line(color =  "orange") +
  geom_point(color =  "orange") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs( x="",y = ""))

```

### Fundo de maneio

```{r}

renderPlotly(
  data() %>% 
  filter(month(date) == 12) %>%
  ggplot(aes(x = date, y = abs(kpi0002), group = 1)) +
  geom_line(color =  "orange") +
  geom_point(color =  "orange") +
  labs( x="",y = "")
  )

```

### Liquidez geral

```{r}

renderPlotly(
  data() %>% 
  filter(month(date) == 12) %>%
  ggplot(aes(x = date, y = abs(kpi0003), group = 1)) +
  geom_line(color =  "orange") +
  geom_point(color =  "orange") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs( x="",y = "")
  )

```

Column {data-width=333}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Margem bruta

```{r}

renderPlotly(
  data() %>% 
  filter(month(date) == 12) %>% 
  ggplot(aes(x = date, y = abs(kpi0007), group = 1)) +
  geom_line(color =  "orange") +
  geom_point(color =  "orange") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs( x="",y = "")
)

```

### Margem Ebitda

```{r}

renderPlotly(
  data() %>% 
  filter(month(date) == 12) %>%
  ggplot(aes(x = date, y = abs(kpi0008), group = 1)) +
  geom_line(color =  "orange") +
  geom_point(color =  "orange") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs( x="",y = "")

)

```

Column {data-width=333}
-----------------------------------------------------------------------

### Net Debt to Ebitda

```{r}

renderPlotly(
  plot <- data() %>% 
  filter(month(date) == 12) %>%
  ggplot(aes(x = date, y = abs(kpi0004), group = 1)) +
  geom_line(color =  "orange") +
  geom_point(color =  "orange") +
  labs( x="",y = "")
)

```

### Monitorização art 35º

```{r}

renderValueBox(
valueBox(value = prettyNum(data() %>% 
                              filter(month(date) == 12) %>% 
                              filter(date == max(date)) %>% 
                              select(kpi0005) %>%  
                              mutate(kpi0005 = scales::percent(kpi0005)), decimal.mark = ".") ,
         caption = "Capital própio no Capial social",
         icon = "ion-quote"))

```

### Reservas legais

```{r}

renderValueBox(
  valueBox(value = prettyNum(data() %>% 
                               filter(month(date) == 12) %>% 
                               filter(date == max(date)) %>% 
                               select(kpi0006) %>% 
                               mutate(kpi0006 = scales::percent(kpi0006)), decimal.mark = "."),
           caption = "Peso reservas legais",
           icon = "ion-quote")
)

```


Financials
=======================================================================

```{r}

query <- "SELECT vat_number,account,name_pt, year, month,value, financial_statement
FROM statements AS s
INNER JOIN account AS a 
ON s.account = a.ies_id 
WHERE vat_number = 513259236;"
df <- dbGetQuery(db,query)

df <- df %>% 
  mutate(date = paste0(month,"-",year)) %>% 
  select(-year, -month,-vat_number) %>% 
  spread(date, value) %>% 
  select(rubrica = name_pt, everything())

Encoding(df$rubrica) <- "UTF-8"
  
```


Column {.tabset}
-----------------------------------------------------------------------

### Balance Sheet

```{r}

df %>% 
  filter(financial_statement == "bs") %>%
  select(-financial_statement) %>% 
  DT::datatable(
  #rownames = FALSE,
  extensions = "Buttons",
  options = list(
    # adds buttons
    dom = 'Bfrtip',
    buttons = c("copy", "csv", "excel","pdf","print"),
    # number of entries on display
    pageLength = 100,
    initComplete = JS(
       "function(settings, json) {",
        "$(this.api().table().header()).css({'font-size': '9pt'});",
        "}"
    )), 
  fillContainer = TRUE) %>% 
  DT::formatStyle(colnames(select(df,-financial_statement)), fontSize = "9pt") %>%
  DT::formatStyle("account",
                  target = "row", 
                  fontWeight = styleEqual(c("A00112","A00125","A00126","A00136","A00139","A00145","A00156","A00157","A00158"),
                                          c("bold","bold","bold","bold","bold","bold","bold","bold","bold"))) %>% 
  DT::formatRound(columns = colnames(select(df,-financial_statement,-rubrica,-account)), digits = 0, mark = ".") 

```

### Profit & Loss

```{r}

df %>% 
  filter(financial_statement == "pl") %>%
  select(-financial_statement) %>% 
  DT::datatable(
  #rownames = FALSE,
  extensions = "Buttons",
  options = list(
    # adds buttons
    dom = 'Bfrtip',
    buttons = c("copy", "csv", "excel","pdf","print"),
    # number of entries on display
    pageLength = 100,
    initComplete = JS(
       "function(settings, json) {",
        "$(this.api().table().header()).css({'font-size': '9pt'});",
        "}"
    )), 
  fillContainer = TRUE) %>% 
  DT::formatStyle(colnames(select(df,-financial_statement)), fontSize = "9pt") %>%
  DT::formatStyle("account",
                  target = "row", 
                  fontWeight = styleEqual(c("A00018","A00021","A00024","A00026"),
                                          c("bold","bold","bold","bold"))) %>% 
  DT::formatRound(columns = colnames(select(df,-financial_statement,-rubrica,-account)), digits = 0, mark = ".") 

```

Liquidity {data-navmenu=Details}
=======================================================================


Market
=======================================================================

