INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A90001','Adiantamento de fornecedores','bs','c','a',false,NULL)
,('A90002','Dividas sócios','bs','c','p',false,NULL)
,('A00001','Vendas e serviços prestados','pl',NULL,NULL,false,'Turnover')
,('A00002','Subsídios à exploração','pl',NULL,NULL,false,'Operating grants')
,('A00003','Ganhos/perdas imputados de subsidiárias, associadas e empreendimentos conjuntos','pl',NULL,NULL,false,'Gains/Losses imputaded to subsidiaries, associated, joint ventures')
,('A00004','Variação nos inventários de produção','pl',NULL,NULL,false,'Inventories of production change')
,('A00005','Trabalhos para a própria entidade','pl',NULL,NULL,false,'Own work capitalized')
,('A00006','Custo das mercadorias vendidas e das matérias consumidas','pl',NULL,NULL,false,'Cost of goods sold and consumed')
,('A00007 ','Fornecimento e serviços externos','pl',NULL,NULL,false,'External supplies and services')
,('A00008','Gastos com pessoal','pl',NULL,NULL,false,'Employees expenses')
;
INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A00009','Imparidade (perdas/reversões)','pl',NULL,NULL,false,'')
,('A00011','Imparidade de dívidas a receber (perdas/reversões)','pl',NULL,NULL,false,'Impairment of debts (losses/reversions)')
,('A00012','Provisões (aumentos/reduções)','pl',NULL,NULL,false,'Provisions (increases/decreases)')
,('A00014','Outras imparidades (perdas/reversões)','pl',NULL,NULL,false,'Impairment-other (losses/reversions)')
,('A00015','Aumentos / reduções de justo valor','pl',NULL,NULL,false,'Increases/decreases of fair value')
,('A00016','Outros rendimentos','pl',NULL,NULL,false,'Other revenues and gains')
,('A00017','Outros gastos','pl',NULL,NULL,false,'Other expenses and losses')
,('A00018','Resultado antes de depreciações, gastos de financiamento e impostos','pl',NULL,NULL,true,'Result before taxes, interests, depreciation and amortisation')
,('A00019','Gastos / reversões de depreciação e de amortização','pl',NULL,NULL,false,'Expenses/reversions of depreciation and amortisation')
,('A00020','Imparidade de investimentops depreciáveis / amortizáveis (perdas / reversões)','pl',NULL,NULL,false,'Imparities of depreciable/amortisable investments (losses/reversions)')
;
INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A00021','Resultado operacional (antes de gastos de financiamento e impostos)','pl',NULL,NULL,true,'Result before interests and taxes')
,('A00022','Juros e rendimentos similiares obtidos','pl',NULL,NULL,false,'Interests and similary revenues')
,('A00023','Juros e gastos similares obtidos','pl',NULL,NULL,false,'Interests and similary expenses')
,('A00024','Resultado antes de impostos','pl',NULL,NULL,true,'Result before taxes')
,('A00025','Imposto sobre o rendimento do periodo','pl',NULL,NULL,false,'Income tax for the period')
,('A00026','Resultado líquido do período','pl',NULL,NULL,true,'Net result for the period')
,('A00027','Resultado das atividades descontínuadas (líquido de impostos) incluíndo no resultado líquido do período','pl',NULL,NULL,true,'Net result-discontinued activities')
,('A00101','Ativos fixos tangíveis','bs','nc','a',false,'Tangible fixed assets')
,('A00102','Propriedades de investimento','bs','nc','a',false,'Investment properties')
,('A00103','Goodwill','bs','nc','a',false,'Goodwill')
;
INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A00104','Ativos intangíveis','bs','nc','a',false,'Intangible assets')
,('A00105','Ativos biológicos','bs','nc','a',false,'Biological assets')
,('A00106','Participações financeiras - método da equivalência patrimonial','bs','nc','a',false,'Investments in shareholdings-equity method')
,('A00107','Outros investimentos financeiros','bs','nc','a',false,'Investments in shareholdings-other methods')
,('A00108','Créditos a receber','bs','nc','a',false,'Non current shareholders')
,('A00110','Investimento financeiros','bs','nc','a',false,'Financial investments')
,('A00111','Créditos e outros ativos não correntes','bs','nc','a',false,'Other financial assets')
,('A00113','Inventários','bs','c','a',false,'Inventories')
,('A00114','Ativos biológicos','bs','c','a',false,'Bioligical assets')
,('A00115','Clientes','bs','c','a',false,'Clients')
;
INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A00117','Capital subscrito e não realizado','bs','c','a',false,'Current shareholders')
,('A00120','Ativos financeiros detidos para negociação','bs','c','a',false,'Available-for-sale financial assets')
,('A00122','Ativos não correntes detidos para venda','bs','c ','a',false,'Non current assets held-for-sale')
,('A00123','Outros ativos correntes ','bs','c','a',false,'Other current assets')
,('A00124','Caixa e depósitos bancários','bs','c','a',false,'Cash and cash equivalents')
,('A00126 ','Total do ativo','bs',NULL,'a',true,'Total assets')
,('A00127','Capital subscrito','bs',NULL,'e',false,'Share capital')
,('A00128','Ações (quotas) próprias','bs',NULL,'e',false,'Treasury shares')
,('A00130 ','Prémios de emissão','bs',NULL,'e',false,'Share premium')
,('A00131','Reservas legais','bs',NULL,'e',false,'Legal reserves')
;
INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A00132','Outras reservas','bs',NULL,'e',false,'Other reserves')
,('A00133','Resultados transitados','bs',NULL,'e',false,'Retained earnings')
,('A00135','Ajustamentos / outras variações no capitál próprio','bs',NULL,'e',false,'Other equity changes')
,('A00136 ','Soma capital','bs',NULL,'e',true,'Sum Capital')
,('A00138','Dividendos antecipados','bs',NULL,'e',false,'Antecipated dividends')
,('A00139','Total do capital próprio','bs',NULL,'e',true,'Total equity')
,('A00140','Provisões','bs','nc','p',false,'Provisions')
,('A00141','Financiamentos obtidos','bs','nc','p',false,'Non current financing obtained')
,('A00143','Passivos por impostos diferidos','bs','nc','p',false,'Deferred tax liabilities')
,('A00144','Outras dividas a pagar','bs','nc','p',false,'Other non current payable accounts')
;
INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A00146 ','Fornecedores','bs','c','p',false,'Suppliers')
,('A00147','Adiantamento de clientes','bs','c','p',false,'Advances from clients')
,('A00149','Financiamentos obtidos','bs','c','p',false,'Current financing obtained')
,('A00150','Outras dívidas a pagar','bs','c','p',false,'Other current payable accounts')
,('A00151','Diferimentos','bs','c','p',false,'Deferreds')
,('A00153','Outros passivos financeiros','bs','c','p',false,'Other financial liabilities')
,('A00154','Passivos não correntes detidos para venda','bs','c','p',false,'Non current liabilities held-for-sale')
,('A00156 ','Soma passivos correntes','bs','c','p',true,'Total current liabilities')
,('A00157','Total do passivo','bs',NULL,'p',true,'Total liabilities')
,('A00118','Outros créditos a receber','bs','c','a',false,'Other receivables')
;
INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A00119','Diferimentos','bs','c','a',false,'Deferreds')
,('A00010','Imparidade / ajustamentos de inventários (perdas/reversões)','pl',NULL,NULL,false,'Impairment of inventories (losses/reversions)')
,('A00013','Imparidade de investimentos não depreciáveis /amortizáveis (perdas/reversões)','pl',NULL,NULL,false,'Imparity of non depreciable/amortisable investments (losses/reversions)')
,('A00109','Ativos por impostos diferidos','bs','nc ','a',false,'Deferred tax assets')
,('A00112','Soma ativo não corrente','bs','nc','a',true,'Total non current assets')
,('A00116','Estado e outros entes públicos','bs','c','a',false,'State and other public bodies')
,('A00121','Outros ativos financeiros','bs','c','a',false,'Other current financial assets')
,('A00125','Soma ativo corrente','bs','c','a',true,'Total current assets')
,('A00129','Outros instrumentos de capital próprio','bs',NULL,'e',false,'Other equity instruments')
,('A00134','Excedentes de revalorização','bs',NULL,'e',false,'Revaluation surplus')
;
INSERT INTO public.account (ies_id,name_pt,financial_statement,current_noncurrent,asset_liability_equity,sum_value,name_en) VALUES 
('A00137','Resultado líquido do período','bs',NULL,'e',false,'Net result for the period')
,('A00142','Responsabilidades por beneficios pós-emprego','bs','nc','p',false,'Responsabilities for benefits after employment')
,('A00145','Soma passivo não corrente','bs','nc','p',true,'Total non current liabilities')
,('A00148','Estado e outros entes públcios','bs','c','p',false,'State and other public bodies')
,('A00152','Passivos financeiros detidos para negociação','bs','c','p',false,'Available-for-sale financial liabilities')
,('A00155','Outros passivos correntes','bs','c','p',false,'Other current liabilities')
,('A00158','Total do capital próprio e do passivo','bs',NULL,'p',true,'Total equity and liabilities')
;